# Generated by Django 5.2.7 on 2025-10-09 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nidn', models.CharField(max_length=20, unique=True, verbose_name='Nomor Induk Dosen Nasional')),
                ('user', models.OneToOneField(limit_choices_to={'profile__role': 'DOSEN'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20, unique=True, verbose_name='Nomor Induk Mahasiswa')),
                ('user', models.OneToOneField(limit_choices_to={'profile__role': 'MAHASISWA'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MataKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kode_mk', models.CharField(max_length=10, unique=True, verbose_name='Kode Mata Kuliah')),
                ('dosen_pengampu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mata_kuliah_diampu', to='accounts.dosen')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_huruf', models.CharField(help_text='Contoh: A, B+, C, D, E', max_length=2)),
                ('nilai_angka', models.FloatField(default=0.0)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_mahasiswa', to='accounts.mahasiswa')),
                ('mata_kuliah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai_matakuliah', to='accounts.matakuliah')),
            ],
            options={
                'verbose_name_plural': 'Daftar Nilai',
                'unique_together': {('mahasiswa', 'mata_kuliah')},
            },
        ),
    ]
