# Generated by Django 4.2.6 on 2025-11-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfpost',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
    ]
