# Generated by Django 5.2.7 on 2025-10-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0002_dosen_mahasiswa'),
    ]

    operations = [
        migrations.AddField(
            model_name='drfpost',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/'),
        ),
    ]
