# Generated by Django 5.2.7 on 2025-10-23 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0003_drfpost_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drfpost',
            options={'ordering': ['-uploaded']},
        ),
        migrations.RenameField(
            model_name='drfpost',
            old_name='uploded',
            new_name='uploaded',
        ),
    ]
